name : My CICD pipeline in GitHUb Actions

on:
  push:
  branches: main

jobs:
  build:
    runs-on: ubuntu-latest

steps:
  - uses: action/checkout@v4
  - name: my first step
   run: |
       echo "this is devops Me'
       uname -a
     
